/** Production defaults for Act 3 reveal (iPhone + monitor). Tune via /dev/act-3-reveal. */

export const DEFAULT_ACT3_REVEAL_CONFIG = {
  iphonePath: "/iphone_16_-_free.glb",
  monitorPath: "/monitor_crossover.glb",

  modelTargetSize: 1.35,

  iphoneScale: 1,
  iphoneStartX: 1.32,
  iphoneStartY: 0.04,
  iphoneStartZ: -1.46,
  iphoneEndX: 0.94,
  iphoneEndY: 0.35,
  iphoneEndZ: -0.36,
  iphoneRotationStartX: 0,
  iphoneRotationStartY: -0.6622909661567111,
  iphoneRotationStartZ: 0,
  iphoneRotationEndX: 0,
  iphoneRotationEndY: -0.45,
  iphoneRotationEndZ: 0,

  monitorScale: 1,
  monitorStartX: 0.03,
  monitorStartY: -0.04,
  monitorStartZ: -0.2,
  monitorEndX: -0.8,
  monitorEndY: 0.47,
  monitorEndZ: 0.95,
  monitorRotationStartX: 0,
  monitorRotationStartY: -0.008013782280623747,
  monitorRotationStartZ: 0,
  monitorRotationEndX: 0,
  monitorRotationEndY: 0.25,
  monitorRotationEndZ: 0,

  cameraStartX: 0,
  cameraStartY: 0,
  cameraStartZ: 0.2,
  lookAtStartX: 0,
  lookAtStartY: 0,
  lookAtStartZ: 0,

  cameraEndX: 0,
  cameraEndY: 0.55,
  cameraEndZ: 4.2,
  lookAtEndX: 0,
  lookAtEndY: 0.05,
  lookAtEndZ: 0,

  ambientIntensity: 0.62,
  keyLightIntensity: 1.15,
  keyLightX: 3.5,
  keyLightY: 5,
  keyLightZ: 4,
  fillLightIntensity: 0.45,
  fillLightX: -4,
  fillLightY: 2,
  fillLightZ: 2,

  spotLightEnabled: true,
  spotLightIntensity: 2.4,
  spotLightX: 0.2,
  spotLightY: 7.5,
  spotLightZ: 1.2,
  spotLightTargetX: 0,
  spotLightTargetY: 0.15,
  spotLightTargetZ: 0,
  spotLightAngle: 0.52,
  spotLightPenumbra: 0.65,
  floorPoolEnabled: true,
  floorPoolY: -0.32,
  floorPoolScale: 8.4,
  floorPoolOpacity: 0.55,

  monitorScreenVideo: "/badreception.mp4",
  iphoneScreenVideo: "/badreception.mp4",

  iphoneScreenWidthRatio: 0.85,
  iphoneScreenHeightRatio: 0.915,
  iphoneScreenNormalOffset: 0.012,
  iphoneScreenLocalX: 0.58,
  iphoneScreenLocalY: 0.086,
  iphoneScreenLocalZ: 2.56,
  iphoneScreenRootX: 0,
  iphoneScreenRootY: 0,
  iphoneScreenRootZ: 0,
  iphoneScreenLocalRotX: 0,
  iphoneScreenLocalRotY: 0,
  iphoneScreenLocalRotZ: 0,

  monitorScreenWidthRatio: 0.97,
  monitorScreenHeightRatio: 0.775,
  monitorScreenNormalOffset: 0.012,
  monitorScreenLocalX: 0.2,
  monitorScreenLocalY: 4.436,
  monitorScreenLocalZ: 2.5,
  monitorScreenRootX: 0,
  monitorScreenRootY: 0,
  monitorScreenRootZ: 0,
  monitorScreenLocalRotX: 0,
  monitorScreenLocalRotY: 0,
  monitorScreenLocalRotZ: 0,
};
